# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar'), ('EUR', 'Euro'), ('BRL', 'Real')], max_length=3, unique=True)),
                ('cotizacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
