# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0033_auto_20160713_0236'),
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moneda',
        ),
    ]
