# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
        ('bienes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_app.Moneda'),
        ),
        migrations.AddField(
            model_name='lista',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_app.Moneda'),
        ),
    ]
