# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0002_auto_20160402_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
