# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0004_auto_20160403_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contactos',
            field=models.ManyToManyField(blank=True, to='bienes_app.Contacto'),
        ),
    ]
