# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0005_auto_20160403_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField()),
                ('checked_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoYBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Bien')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='bien',
            field=models.ManyToManyField(through='bienes_app.PedidoYBien', to='bienes_app.Bien'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Cliente'),
        ),
    ]
