# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0006_auto_20160403_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ABR', 'Abierto'), ('CHK', 'Checked-out'), ('COM', 'Completo')], default='ABR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoybien',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
