# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0007_auto_20160407_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ABR', 'Abierto'), ('CHK', 'Checked-out'), ('COM', 'Completo')], default='ABR', max_length=3),
        ),
        migrations.AlterField(
            model_name='pedidoybien',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
