# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0009_pedido_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
