# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0010_auto_20160407_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='bien',
            new_name='bienes',
        ),
    ]
