# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0011_auto_20160407_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bien',
            old_name='imagen',
            new_name='imagen1',
        ),
        migrations.AddField(
            model_name='bien',
            name='imagen2',
            field=models.ImageField(default='Bien/none.png', upload_to='Bien/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='imagen3',
            field=models.ImageField(default='Bien/none.png', upload_to='Bien/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='imagen4',
            field=models.ImageField(default='Bien/none.png', upload_to='Bien/'),
        ),
        migrations.AddField(
            model_name='bien',
            name='imagen5',
            field=models.ImageField(default='Bien/none.png', upload_to='Bien/'),
        ),
    ]
