# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0012_auto_20160417_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='imagen1',
            field=models.ImageField(default='Bien/none.png', upload_to='Bien/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='imagen2',
            field=models.ImageField(blank=True, default='Bien/none.png', upload_to='Bien/'),
        ),
    ]
