# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0014_auto_20160418_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ABR', 'Abierto'), ('CHK', 'Checked-out'), ('PRE', 'En preparación'), ('COM', 'Completo'), ('CAN', 'Cancelado')], default='ABR', max_length=3),
        ),
    ]
