# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0015_auto_20160425_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteYBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visible', models.BooleanField(default=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Bien')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteYClasificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visible', models.BooleanField(default=True)),
                ('clasificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Clasificador')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_fantasia',
            field=models.CharField(default='nombre_fantasia', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='razon_social', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clienteyclasificador',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Cliente'),
        ),
        migrations.AddField(
            model_name='clienteybien',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='clienteyclasificador',
            unique_together=set([('cliente', 'clasificador')]),
        ),
        migrations.AlterUniqueTogether(
            name='clienteybien',
            unique_together=set([('cliente', 'bien')]),
        ),
    ]
