# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0016_auto_20160507_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='partido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='bulto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='plazo_entrega',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cargo',
            field=models.CharField(choices=[('COM', 'Comprador'), ('VEN', 'Vendedor'), ('COB', 'Cobrador'), ('DIR', 'Director'), ('SOC', 'Socio/Dueño'), ('OTR', 'Otro')], default='OTR', max_length=3),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='horario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dias y horas de atención'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre y apellido'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='condicion_comercial',
            field=models.CharField(blank=True, choices=[('30F', '30 días F/F'), ('40F', '40 días F/F'), ('60F', '60 días F/F'), ('C40', 'Cheque contra entrega 40 días F/F'), ('CDO', 'Contado'), ('EFT', 'Efectivo'), ('TRF', 'Transferencia')], max_length=3, null=True, verbose_name='Forma de entrega'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contactos',
            field=models.ManyToManyField(blank=True, to='bienes_app.Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', message='No cumple con el formato de CUIT/CUIL')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_oficial',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_incorporacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='forma_entrega',
            field=models.CharField(blank=True, choices=[('REI', 'Se retira en nuestras instalaciones'), ('EEI', 'Se entrega en nuestras instalaciones'), ('RDI', 'Se retira de nuestras instalaciones')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('EXC', 'Excento'), ('MON', 'Monotributista'), ('NOR', 'No Responsable')], max_length=3, null=True, verbose_name='Condición frente al IVA'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de fantasía'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='partido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(blank=True, choices=[('BIU', 'Bien de uso'), ('GVA', 'Gastos varios'), ('IMP', 'Impuesto'), ('INS', 'Insumo'), ('MPR', 'Materia prima'), ('PTE', 'Producto terminado'), ('SVC', 'Servicio'), ('SBP', 'Subproducto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_factura',
            field=models.CharField(blank=True, choices=[('FTA', 'Factura A'), ('FTB', 'Factura B'), ('FTA', 'Factura A'), ('FTC', 'Factura C'), ('FTE', 'Factura E'), ('FTM', 'Factura M'), ('NCA', 'Nota de crédito A'), ('NCB', 'Nota de crédito B'), ('NCC', 'Nota de crédito C'), ('NCE', 'Nota de crédito E'), ('NCM', 'Nota de crédito M'), ('NDA', 'Nota de débito A'), ('NDB', 'Nota de débito B'), ('NDC', 'Nota de débito C'), ('NDE', 'Nota de débito E'), ('NDM', 'Nota de débito M')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
