# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0017_auto_20160513_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dto1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='dto2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='dto3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
