# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0026_auto_20160515_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Costo de proveedor', 'verbose_name_plural': 'Costos de proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social', 'nombre_fantasia'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='razon social prueba', max_length=50),
            preserve_default=False,
        ),
    ]
