# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0018_auto_20160515_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Rubro'),
            preserve_default=False,
        ),
    ]
