# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 14:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0019_auto_20160515_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='agente_perc_iibb',
            field=models.BooleanField(default=False, verbose_name='Agente percepcion de IIBB'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='agente_perc_iigg',
            field=models.BooleanField(default=False, verbose_name='Agente percepcion de IIGG'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='agente_perc_iva',
            field=models.BooleanField(default=False, verbose_name='Agente percepcion de IVA'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='agente_perc_ss',
            field=models.BooleanField(default=False, verbose_name='Agente percepcion de seguridad social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='alerta',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comprobante_cuit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicion_comercial',
            field=models.CharField(blank=True, choices=[('30F', '30 días F/F'), ('40F', '40 días F/F'), ('60F', '60 días F/F'), ('C40', 'Cheque contra entrega 40 días F/F'), ('CDO', 'Contado'), ('EFT', 'Efectivo'), ('TRF', 'Transferencia')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='corredor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$', message='No cumple con el formato de CUIT/CUIL')]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='expreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Expreso'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_incorporacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_entrega',
            field=models.CharField(blank=True, choices=[('REI', 'Se retira en nuestras instalaciones'), ('EEI', 'Se entrega en nuestras instalaciones'), ('RDI', 'Se retira de nuestras instalaciones')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='informe_economico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('EXC', 'Excento'), ('MON', 'Monotributista'), ('NOR', 'No Responsable')], max_length=3, null=True, verbose_name='Condición frente al IVA'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='jurisdiccion_iibb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Límite de crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mayorista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_factura',
            field=models.CharField(blank=True, choices=[('FTA', 'Factura A'), ('FTB', 'Factura B'), ('FTA', 'Factura A'), ('FTC', 'Factura C'), ('FTE', 'Factura E'), ('FTM', 'Factura M'), ('NCA', 'Nota de crédito A'), ('NCB', 'Nota de crédito B'), ('NCC', 'Nota de crédito C'), ('NCE', 'Nota de crédito E'), ('NCM', 'Nota de crédito M'), ('NDA', 'Nota de débito A'), ('NDB', 'Nota de débito B'), ('NDC', 'Nota de débito C'), ('NDE', 'Nota de débito E'), ('NDM', 'Nota de débito M')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='condicion_comercial',
            field=models.CharField(blank=True, choices=[('30F', '30 días F/F'), ('40F', '40 días F/F'), ('60F', '60 días F/F'), ('C40', 'Cheque contra entrega 40 días F/F'), ('CDO', 'Contado'), ('EFT', 'Efectivo'), ('TRF', 'Transferencia')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='forma_entrega',
            field=models.CharField(blank=True, choices=[('REI', 'Se retira en nuestras instalaciones'), ('EEI', 'Se entrega en nuestras instalaciones'), ('RDI', 'Se retira de nuestras instalaciones')], max_length=3, null=True, verbose_name='Forma de entrega'),
        ),
    ]
