# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0020_atributosbien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('titulo',),
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.RemoveField(
            model_name='atributosbien',
            name='bien',
        ),
        migrations.DeleteModel(
            name='AtributosBien',
        ),
    ]
