# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0020_auto_20160515_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='email_oficial',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_incorporacion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_incorporacion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 5, 15, 14, 18, 28, 441539, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
