# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0022_remove_cliente_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 5, 15, 14, 24, 57, 753806, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
