# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0022_auto_20160515_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atributosbien',
            unique_together=set([('bien', 'atributo')]),
        ),
    ]
