# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0023_cliente_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(),
        ),
    ]
