# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0024_auto_20160515_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(null=True),
        ),
    ]
