# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0026_auto_20160519_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.CharField(max_length=20, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bien',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Impuesto'),
        ),
    ]
