# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0027_auto_20160520_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='checked_out',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='completo',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('ABR', 'Abierto'), ('CHK', 'Confirmado'), ('PRE', 'En preparación'), ('COM', 'Completo'), ('CAN', 'Cancelado')], default='ABR', max_length=3),
        ),
    ]
