# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0028_auto_20160523_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
