# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 19:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0029_auto_20160523_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_prevista_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Proveedor'),
        ),
        migrations.AddField(
            model_name='pedidoybien',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoybien',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Solo cantidades positivas.')]),
        ),
    ]
