# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0030_auto_20160706_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cerrado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Estado',
            field=models.CharField(choices=[('ABR', 'Abierto'), ('CHK', 'Confirmado por cliente'), ('PRE', 'En preparación'), ('COM', 'Completo'), ('CAN', 'Cancelado')], default='ABR', max_length=3),
        ),
        migrations.AddField(
            model_name='pedidoybien',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidoybien',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
