# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0031_auto_20160706_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Estado',
            new_name='estado',
        ),
    ]
