# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0033_auto_20160713_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoybien',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
