# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0035_auto_20160716_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='confirmado_x_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
