# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 18:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0036_auto_20160804_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': (('action_proforma', 'Ejecutar acciones'),),
            },
        ),
        migrations.CreateModel(
            name='ProformaYBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Solo cantidades positivas.')])),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Bien')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Proforma')),
            ],
        ),
        migrations.AddField(
            model_name='proforma',
            name='bienes',
            field=models.ManyToManyField(through='bienes_app.ProformaYBien', to='bienes_app.Bien'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Cliente'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='pedidos',
            field=models.ManyToManyField(to='bienes_app.Pedido'),
        ),
    ]
