# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0037_auto_20160806_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='validado_x_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
