# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0038_auto_20160814_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaybien',
            name='_precio',
            field=models.DecimalField(blank=True, db_column='precio', decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
