# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-14 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0040_remove_proformaybien__precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformaybien',
            name='bien',
        ),
        migrations.AddField(
            model_name='proformaybien',
            name='item',
            field=models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, to='bienes_app.PedidoYBien'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proforma',
            name='bienes',
            field=models.ManyToManyField(through='bienes_app.ProformaYBien', to='bienes_app.PedidoYBien'),
        ),
    ]
