# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0041_auto_20160814_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoybien',
            name='cantidad_entregada',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cerrado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='proformaybien',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bienes_app.PedidoYBien'),
        ),
    ]
