# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bienes_app', '0043_auto_20160816_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoybien',
            options={'verbose_name_plural': ' Pedidos (detalle)'},
        ),
        migrations.AlterModelOptions(
            name='proforma',
            options={'permissions': (('action_proforma', 'Ejecutar acciones'),), 'verbose_name_plural': ' Proformas'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='validado_x_admin',
            field=models.BooleanField(default=False, help_text='Editable solo por admin', verbose_name='Validado'),
        ),
    ]
