# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 00:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0047_auto_20160826_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaybien',
            name='cantidad',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0, message='Solo cantidades positivas.')]),
        ),
    ]
