# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-07 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0049_auto_20160901_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 9, 7, 17, 52, 0, 109049, tzinfo=utc), verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pedidoybien',
            unique_together=set([('pedido', 'bien')]),
        ),
    ]
