# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0050_auto_20160907_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
