# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-11 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0051_proforma_cancelada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_alta',
            new_name='fecha_creacion',
        ),
    ]
