# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0052_auto_20160911_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='presupuesto',
            field=models.BooleanField(default=False),
        ),
    ]
