# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0053_pedido_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='presupuesto',
            field=models.BooleanField(default=False, verbose_name='Es Presupuesto?'),
        ),
    ]
