# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 17:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0054_auto_20160916_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('factor', models.IntegerField(blank=True, null=True)),
                ('letra', models.CharField(blank=True, max_length=3, null=True)),
                ('codigoafip', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('circuito', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=50)),
                ('plazo_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100)),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoClasificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('denominacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='partido',
        ),
        migrations.AddField(
            model_name='bien',
            name='e',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='primeros_4_digitos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999, message='Hasta 4 digitos.')]),
        ),
        migrations.AddField(
            model_name='bien',
            name='r',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clasificador',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clasificador',
            name='publicidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clasificador',
            name='rango',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clasificador',
            name='regalias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condicion_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.CondicionComercial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='forma_entrega',
            field=models.CharField(blank=True, choices=[('C1', 'Retira de nuestras instalaciones'), ('C2', 'Entrega en las instalaciones del cliente'), ('C3', 'Entrega en expresso indicado por el cliente')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Localidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Pais'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Comprobantes'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='condicion_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.CondicionComercial'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='forma_entrega',
            field=models.CharField(blank=True, choices=[('P1', 'Entrega en nuestras instalaciones'), ('P2', 'Retira de las instalaciones del proveedor'), ('P3', 'Entrega en expresso designado por nosotros')], max_length=3, null=True, verbose_name='Forma de entrega'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Localidad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Pais'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Provincia'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.Comprobantes'),
        ),
        migrations.AddField(
            model_name='clasificador',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.TipoClasificador'),
        ),
    ]
