# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0056_auto_20161211_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='provincia',
        ),
    ]
