# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0061_auto_20161211_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantes',
            name='factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
