# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0063_auto_20161212_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='jurisdiccion_iibb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiccion_localidad', to='bienes_app.Localidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_localidad', to='bienes_app.Localidad'),
        ),
    ]
