# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0066_auto_20161212_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
