# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0068_auto_20161212_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('orden', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rubro',
            options={'ordering': ['rubro'], 'verbose_name_plural': 'Rubros'},
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='denominacion',
        ),
        migrations.AddField(
            model_name='rubro',
            name='imagen',
            field=models.CharField(default='NULO', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubro',
            name='orden',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubro',
            name='rubro',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubro',
            name='tipoi',
            field=models.CharField(choices=[('NULO', 'Nulo'), ('MEDIO', 'Medio'), ('COMPLETO', 'Completo')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
