# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0069_auto_20161212_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Division'),
        ),
    ]
