# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0070_rubro_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='lote_optim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='stock_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='stock_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='bulto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='clasificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Clasificador'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='denominacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bien',
            name='forma_abastecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Abastecimiento'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bienes_app.Marca'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='unidad',
            field=models.CharField(blank=True, choices=[('UN', 'Unidades'), ('KG', 'Kilogramos'), ('MT', 'Metros'), ('LT', 'Litros')], default='UN', max_length=5, null=True),
        ),
    ]
