# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0071_auto_20161212_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='metroxkg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
