# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0072_bien_metroxkg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='imagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='tipoi',
            field=models.CharField(blank=True, choices=[('NULO', 'Nulo'), ('MEDIO', 'Medio'), ('COMPLETO', 'Completo')], max_length=200, null=True),
        ),
    ]
