# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0073_auto_20170107_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Marca/'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Rubro/'),
        ),
    ]
